# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TopMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopMovies
  pod 'ProgressHUD', '~> 13.6'
  pod "ColorHex", '~> 2.1.1'
  pod 'ObjectMapper', '~> 4.2'
  pod 'SwiftHTTP', '~> 3.0.1'
  pod 'Log', '~> 2.0'
  pod 'ReachabilitySwift', '~> 5.0.0'
  pod 'Toast-Swift', '~> 5.0.1'
  
  target 'TopMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TopMoviesUITests' do
    # Pods for testing
  end

end
